-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `cdntaxreceipts_advantage`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * cdntaxreceipts_advantage
-- *
-- * Holds description for advantage for each contribution
-- *
-- *******************************************************/
CREATE TABLE `cdntaxreceipts_advantage` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique CdnAdvantage ID',
  `contribution_id` int unsigned COMMENT 'FK to Contribution',
  `advantage_description` varchar(255) COMMENT 'Description of Advantage',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
